import type { WorkspaceSnapshot } from "@/lib/screenit-types";

export const demoWorkspace: WorkspaceSnapshot = {
  source: "demo",
  positions: [
    {
      id: "pos-service-desk",
      title: "Service Desk Technician",
      department: "Technical Operations",
      location: "Naples, FL · Hybrid",
      status: "active",
      candidateCount: 5,
      reviewCount: 2,
      requirements: [
        "Two or more years supporting Microsoft 365 users",
        "Clear customer communication and ticket documentation",
        "Experience troubleshooting Windows endpoints",
      ],
      questions: [
        {
          id: "q1",
          prompt: "Walk me through your recent Microsoft 365 support experience.",
          reason: "Confirms the role's primary technical requirement.",
          required: true,
        },
        {
          id: "q2",
          prompt: "Tell me about a difficult customer issue and how you communicated the next steps.",
          reason: "Looks for job-related communication evidence.",
          required: true,
        },
        {
          id: "q3",
          prompt: "Your resume mentions endpoint management. Which tools did you use and what did you own?",
          reason: "Clarifies a resume claim without making assumptions.",
          required: true,
        },
      ],
      createdAt: "2026-07-18T14:00:00.000Z",
    },
    {
      id: "pos-project-coordinator",
      title: "IT Project Coordinator",
      department: "Projects",
      location: "Naples, FL",
      status: "draft",
      candidateCount: 0,
      reviewCount: 0,
      requirements: [
        "Own project schedules and customer follow-up",
        "Coordinate procurement and technical resources",
      ],
      questions: [],
      createdAt: "2026-07-20T16:30:00.000Z",
    },
  ],
  candidates: [
    {
      id: "candidate-jordan",
      positionId: "pos-service-desk",
      name: "Jordan Lee",
      email: "jordan.lee@example.com",
      phone: "+1 (239) 555-0148",
      stage: "review",
      resumeFileName: "Jordan-Lee-Resume.pdf",
      resumeHighlights: [
        "Three years of Microsoft 365 and Windows support",
        "Worked in a 20-person managed services help desk",
        "Lists Intune, Entra ID, HaloPSA, and Datto RMM",
      ],
      resumeClarifications: ["Ask for a specific complex Windows troubleshooting example."],
      screeningQuestions: [],
      interviewMode: "browser",
      scheduledAt: "2026-07-21T14:30:00.000Z",
      completedAt: "2026-07-21T14:54:00.000Z",
      inviteToken: "7d439e73652b419eb0af00cb31f6f194",
      inviteExpiresAt: "2026-08-21T14:30:00.000Z",
      createdAt: "2026-07-19T13:15:00.000Z",
    },
    {
      id: "candidate-maya",
      positionId: "pos-service-desk",
      name: "Maya Thompson",
      email: "maya.thompson@example.com",
      phone: "+1 (239) 555-0182",
      stage: "invited",
      resumeFileName: "Maya-Thompson.docx",
      resumeHighlights: [
        "Customer support and Microsoft 365 administration",
        "CompTIA A+ certified",
      ],
      resumeClarifications: [],
      screeningQuestions: [],
      interviewMode: "phone",
      scheduledAt: "2026-07-22T15:00:00.000Z",
      completedAt: null,
      inviteToken: "366cc1c772154b6c8512eb9ff9ce6092",
      inviteExpiresAt: "2026-08-22T15:00:00.000Z",
      createdAt: "2026-07-20T11:05:00.000Z",
    },
    {
      id: "candidate-alex",
      positionId: "pos-service-desk",
      name: "Alex Rivera",
      email: "alex.rivera@example.com",
      phone: null,
      stage: "new",
      resumeFileName: "Alex-Rivera-Resume.pdf",
      resumeHighlights: ["Desktop support background", "Bilingual English and Spanish"],
      resumeClarifications: ["Clarify the duration and scope of Microsoft 365 support experience."],
      screeningQuestions: [],
      interviewMode: null,
      scheduledAt: null,
      completedAt: null,
      inviteToken: "ac7829420ffd4820ae199679d6b3b239",
      inviteExpiresAt: "2026-08-21T12:12:00.000Z",
      createdAt: "2026-07-21T12:12:00.000Z",
    },
  ],
  reports: [
    {
      id: "report-jordan",
      candidateId: "candidate-jordan",
      summary:
        "Jordan described hands-on Microsoft 365 support in an MSP environment and gave a specific example of owning a customer escalation. Two areas need recruiter clarification before the next interview.",
      evidence: [
        {
          requirement: "Two or more years supporting Microsoft 365 users",
          level: "demonstrated",
          evidence: "Described three years administering Exchange Online, Entra ID, and Microsoft 365 licensing.",
        },
        {
          requirement: "Clear customer communication and ticket documentation",
          level: "demonstrated",
          evidence: "Explained a recurring update cadence and documented each troubleshooting step in HaloPSA.",
        },
        {
          requirement: "Experience troubleshooting Windows endpoints",
          level: "partial",
          evidence: "Discussed endpoint patching and remote support, but did not describe a complex Windows incident.",
        },
      ],
      clarifications: [
        "Confirm willingness to participate in the rotating after-hours schedule.",
        "Ask for a deeper Windows troubleshooting example.",
      ],
      recommendation: "recruiter_review",
      roleAlignment: "partial_alignment",
      fitRationale: "The interview demonstrates the core Microsoft 365 and customer communication requirements. A deeper Windows troubleshooting example is still needed.",
      statedMotivation: "Jordan said they enjoy solving user-impacting problems and keep learning through hands-on lab work.",
      conversationSignals: [
        { signal: "Ownership", evidence: "Described personally carrying a customer escalation through follow-up and resolution." },
        { signal: "Clear handoff", evidence: "Explained what another technician would need in the ticket notes to continue the work." },
      ],
      generatedAt: "2026-07-21T14:56:00.000Z",
    },
  ],
};
