-- ═══════════════════════════════════════════════════════════════════════
-- Seed default skills for all worker agents
-- These are base knowledge skills that teach each agent common procedures,
-- troubleshooting steps, and vendor-specific knowledge for their domain.
-- ═══════════════════════════════════════════════════════════════════════

-- ── Dwight Schrute (Documentation / Hudu) ─────────────────────────────

INSERT INTO agent_skills (agent_name, title, content, skill_type) VALUES
('dwight_schrute', 'Hudu Search Strategy', E'When searching Hudu for client documentation:\n1. Always search by company name first, then by asset type\n2. Check the company''s "Processes" section for step-by-step procedures\n3. Look in "Passwords" for credentials related to the issue\n4. Check "Asset Layouts" for network diagrams and IP schemes\n5. Search Knowledge Base articles for client-specific procedures\n6. Check "Magic Dash" dashboards for at-a-glance client info\n\nHudu API endpoints to use:\n- GET /api/v1/companies — list/search companies\n- GET /api/v1/articles — search KB articles\n- GET /api/v1/asset_passwords — get credentials\n- GET /api/v1/assets — get assets by layout\n\nAlways include direct Hudu links in your findings so the tech can click through.', 'procedure'),

('dwight_schrute', 'Common Documentation Gaps', E'Flag these documentation gaps when found:\n- No network diagram for the client\n- Missing admin credentials (firewall, switches, servers)\n- No documented backup schedule or DR plan\n- Missing ISP/circuit information\n- No escalation contacts or SLA details\n- Outdated OS versions in asset records\n- No documented VPN configuration\n\nSuggest the tech update documentation after resolving the ticket.', 'instruction'),

('dwight_schrute', 'IT Glue Migration Notes', E'If a client was migrated from IT Glue to Hudu:\n- Check for legacy naming conventions (IT Glue uses "Organizations", Hudu uses "Companies")\n- Flexible Assets in IT Glue map to Asset Layouts in Hudu\n- Embedded Passwords may need re-linking after migration\n- Check both the company page AND global search for documentation\n- Some migrated articles may have broken formatting — check the original if content looks garbled', 'context');

-- ── Jim Halpert (Identity / JumpCloud) ────────────────────────────────

INSERT INTO agent_skills (agent_name, title, content, skill_type) VALUES
('jim_halpert', 'JumpCloud Troubleshooting', E'Common JumpCloud issues and resolution steps:\n\n## User Cannot Login\n1. Check user status in JumpCloud console — is the account active?\n2. Verify password hasn''t expired (Settings > Password Policy)\n3. Check if MFA is enrolled and working (User > Security tab)\n4. Verify user''s device is bound to their JumpCloud account\n5. Check system logs: `journalctl -u jcagent` (Linux) or Event Viewer (Windows)\n\n## Device Not Checking In\n1. Check JumpCloud agent service: `systemctl status jcagent` (Linux) or `Get-Service "JumpCloud Agent"` (Windows)\n2. Restart agent: `sudo systemctl restart jcagent` or `Restart-Service "JumpCloud Agent"`\n3. Verify network: device must reach `console.jumpcloud.com` on port 443\n4. Check agent version — update if outdated: `apt-get update && apt-get install jcagent`\n5. Re-install agent if corrupted: download installer from JumpCloud console > Systems > Add\n\n## MFA Issues\n1. If TOTP not working, check device clock sync (NTP)\n2. Admin can reset MFA: User > Security > Reset MFA\n3. If push notifications not received, verify Protect app is installed and registered\n4. Fallback: admin can generate temporary bypass code', 'runbook'),

('jim_halpert', 'JumpCloud Policy Compliance', E'When checking policy compliance:\n- System Policies: verify OS updates, disk encryption, firewall enabled\n- User Policies: password complexity, MFA enforcement, session timeout\n- Conditional Access: check if location/device restrictions apply\n- RADIUS: verify RADIUS server config for WiFi/VPN auth\n- LDAP: check LDAP bind status for legacy app integration\n\nKB: https://support.jumpcloud.com/support/home\nAPI: https://docs.jumpcloud.com/api/', 'instruction');

-- ── Andy Bernard (Endpoint/RMM / Datto) ───────────────────────────────

INSERT INTO agent_skills (agent_name, title, content, skill_type) VALUES
('andy_bernard', 'Datto RMM Quick Jobs', E'Quick Jobs are your fastest remediation tool in Datto RMM. Common Quick Jobs:\n\n## Network Troubleshooting\n- "Flush DNS": Push to clear DNS cache when sites not resolving\n- "Network Reset": Reset TCP/IP stack, flush DNS, renew DHCP\n- "Ping Test": Run ping/tracert to diagnose connectivity\n\n## System Maintenance\n- "Clear Print Spooler": Fix stuck print jobs\n- "Restart Service": Restart a specific Windows service\n- "Disk Cleanup": Run Windows disk cleanup to free space\n- "Force Group Policy Update": `gpupdate /force`\n- "Clear Temp Files": Remove temp/cache files\n\n## Monitoring\n- "Top Processes": Get CPU/memory usage by process\n- "Event Log Export": Pull recent Windows event logs\n- "Disk Space Check": Get detailed disk usage report\n- "Installed Software": List all installed applications\n\n## Patching\n- "Windows Update Scan": Force check for missing updates\n- "Install Pending Patches": Apply approved patches immediately\n- "DISM/SFC Repair": Run `DISM /Online /Cleanup-Image /RestoreHealth` + `sfc /scannow`\n\nAlways suggest the specific Quick Job or component in your findings.', 'procedure'),

('andy_bernard', 'Datto RMM Alert Interpretation', E'Common Datto monitoring alert types and what they mean:\n\n- **Disk Space Critical**: Drive usage >90% — check for large files, old backups, temp files\n- **CPU High**: Sustained CPU >90% — check top processes, look for crypto miners or runaway apps\n- **Memory Critical**: RAM usage >95% — check for memory leaks, recommend reboot\n- **Service Stopped**: A monitored service crashed — check event logs, restart service\n- **Offline**: Device not seen for 15+ min — could be shutdown, network issue, or hardware failure\n- **Patch Overdue**: Missing critical patches for 7+ days — check WSUS, patch policy\n- **AV Definition Outdated**: Antivirus definitions stale — may indicate AV service issue\n- **SSL Certificate Expiring**: Certificate expires within 30 days — renew ASAP\n- **Backup Failed**: Backup job failed — check Cove/Veeam/backup service logs\n\nFor each alert, include the alert severity, affected device hostname, and recommended action.', 'instruction');

-- ── Stanley Hudson (Cloud / Vultr) ────────────────────────────────────

INSERT INTO agent_skills (agent_name, title, content, skill_type) VALUES
('stanley_hudson', 'Vultr Instance Troubleshooting', E'Common Vultr cloud instance issues:\n\n## Instance Unreachable\n1. Check instance status in Vultr dashboard — is it running?\n2. Use Vultr console (web-based VNC) to access if SSH is down\n3. Check firewall rules in Vultr dashboard — port 22/443 open?\n4. Verify instance hasn''t exceeded bandwidth allocation\n5. Check if IP is blocklisted (DDoS mitigation may have triggered)\n\n## High Resource Usage\n1. Check CPU/RAM graphs in Vultr dashboard\n2. SSH in and run `htop` or `top` to identify processes\n3. Check disk usage: `df -h` and `du -sh /var/log/*`\n4. Review recent deployments — new code may have memory leak\n\n## DNS Issues\n1. Verify A/AAAA records point to correct Vultr IP\n2. Check TTL — recent changes may not have propagated\n3. Verify reverse DNS is set in Vultr dashboard (important for email)\n4. Use `dig` or MX Toolbox to verify DNS resolution\n\nVultr API: https://www.vultr.com/api/\nVultr Status: https://status.vultr.com/', 'runbook'),

('stanley_hudson', 'Cloud Infrastructure Best Practices', E'General cloud troubleshooting approach:\n1. Check provider status page FIRST — is there an outage?\n2. Verify instance/VM is in the correct state (running, not stopped)\n3. Check security groups/firewall rules for access issues\n4. Review logs: `/var/log/syslog`, `/var/log/auth.log`, application logs\n5. Check resource utilization — may need to resize/upgrade\n6. Verify DNS propagation if domain-related\n7. Check SSL certificate expiry for HTTPS issues\n8. Review recent changes — was anything deployed recently?\n\nAlways include the instance ID, IP address, and region in your findings.', 'instruction');

-- ── Phyllis Vance (Email/DNS / MX Toolbox) ────────────────────────────

INSERT INTO agent_skills (agent_name, title, content, skill_type) VALUES
('phyllis_vance', 'Email Deliverability Troubleshooting', E'Step-by-step email deliverability diagnosis:\n\n## Emails Going to Spam\n1. Check SPF record: `dig TXT yourdomain.com` — verify `v=spf1` includes all sending IPs\n2. Check DKIM: verify selector record exists and matches signing key\n3. Check DMARC: `dig TXT _dmarc.yourdomain.com` — should have `p=quarantine` or `p=reject`\n4. Check MX Toolbox blacklist: https://mxtoolbox.com/blacklists.aspx\n5. Check sending IP reputation: https://senderscore.org/\n6. Review message headers for SPF/DKIM/DMARC pass/fail results\n7. Check if domain is new — new domains have low reputation initially\n\n## Emails Not Received\n1. Check MX records: `dig MX yourdomain.com` — verify they point to correct mail server\n2. Check mail server is responding: `telnet mail.yourdomain.com 25`\n3. Check Exchange/M365 message trace for delivery status\n4. Check spam quarantine in M365 or spam filter\n5. Verify no mail flow rules are redirecting/blocking\n6. Check recipient mailbox size — may be full\n\n## Common DNS Record Issues\n- SPF "too many lookups" (max 10 DNS lookups) — consolidate includes, use ip4/ip6 instead\n- DKIM key rotation needed — old selector may be expired\n- DMARC `p=none` provides no protection — recommend upgrading to `p=quarantine`\n- Duplicate MX records cause intermittent delivery failures', 'runbook'),

('phyllis_vance', 'Microsoft 365 Mail Flow', E'M365-specific email troubleshooting:\n- Message Trace: Exchange Admin Center > Mail Flow > Message Trace\n- Transport Rules: check for rules blocking/redirecting mail\n- Connector Issues: verify inbound/outbound connectors if using smart host\n- Quarantine: Security & Compliance Center > Threat Management > Review\n- SPF for M365: include `include:spf.protection.outlook.com`\n- DKIM for M365: enable in Exchange Admin Center > Protection > DKIM\n\nMicrosoft 365 Admin: https://admin.microsoft.com\nExchange Admin: https://admin.exchange.microsoft.com\nSecurity Center: https://security.microsoft.com', 'instruction');

-- ── Angela Martin (Security) ──────────────────────────────────────────

INSERT INTO agent_skills (agent_name, title, content, skill_type) VALUES
('angela_martin', 'Security Incident Response', E'When a security incident is detected:\n\n## Immediate Actions\n1. CONTAIN: Isolate affected devices from network (disable NIC, quarantine in EDR)\n2. PRESERVE: Do NOT reboot — preserve volatile evidence (RAM, connections)\n3. DOCUMENT: Record timeline of events, affected systems, indicators of compromise\n4. NOTIFY: Alert client contact and internal escalation chain\n\n## Common Threat Indicators\n- Unusual login times or locations (check Azure AD / JumpCloud sign-in logs)\n- New mail forwarding rules (check Exchange admin — common in BEC)\n- MFA registration from unknown device\n- PowerShell execution with encoded commands\n- Outbound connections to known C2 IPs (check firewall logs)\n- New admin accounts or privilege escalation\n- Files encrypted with unusual extensions (ransomware)\n\n## BEC (Business Email Compromise) Response\n1. Reset user password immediately\n2. Revoke all active sessions in Azure AD\n3. Check mail forwarding rules — remove any unauthorized\n4. Review sent items for sent phishing emails\n5. Enable MFA if not already enabled\n6. Review sign-in logs for unauthorized access\n7. Notify affected parties if data was exposed\n\nMicrosoft Security: https://security.microsoft.com\nVirusTotal: https://www.virustotal.com\nAbuseIPDB: https://www.abuseipdb.com', 'runbook'),

('angela_martin', 'Security Baseline Checks', E'Quick security posture checks for any ticket:\n- Is MFA enabled for all users? (especially admins)\n- Are admin accounts using dedicated accounts (not daily-driver accounts)?\n- Is conditional access configured for risky sign-ins?\n- Are legacy authentication protocols disabled?\n- Is email authentication configured (SPF, DKIM, DMARC)?\n- Are endpoints running current AV/EDR?\n- Is disk encryption enabled on all endpoints?\n- Are firewall rules restrictive (deny-by-default)?\n\nFlag any gaps found during triage — don''t wait for a dedicated security review.', 'instruction');

-- ── Kelly Kapoor (VoIP/Telephony / 3CX + Twilio) ─────────────────────

INSERT INTO agent_skills (agent_name, title, content, skill_type) VALUES
('kelly_kapoor', '3CX Troubleshooting Guide', E'Common 3CX issues and fixes:\n\n## Calls Not Connecting\n1. Check trunk registration status in 3CX Dashboard > SIP Trunks\n2. If trunk shows "Failed", check credentials and SIP server address\n3. Verify firewall allows SIP (5060/UDP) and RTP (9000-10999/UDP)\n4. Check if SBC (Session Border Controller) is running if deployed\n5. Test with a different trunk to isolate the issue\n\n## Audio Quality Issues\n1. Check QoS settings — SIP/RTP traffic should be prioritized\n2. Test bandwidth: run speed test from the VoIP VLAN\n3. Check for jitter/packet loss: `ping -f -l 1472 sip.provider.com`\n4. Verify codec settings: G.711 for LAN, G.729 for WAN\n5. Check if calls traverse NAT — may need STUN/TURN configuration\n\n## Extension Not Registering\n1. Check extension is enabled in 3CX Management Console\n2. Verify credentials on the IP phone/softphone\n3. Check phone''s network — can it reach the 3CX server?\n4. Factory reset the phone and re-provision\n5. Check DHCP option 66 for auto-provisioning\n\n3CX Admin: https://www.3cx.com/docs/manual/\n3CX Status: https://status.3cx.com/', 'runbook'),

('kelly_kapoor', 'Twilio SIP Trunk Troubleshooting', E'Twilio-specific VoIP issues:\n- Check trunk status in Twilio Console > Elastic SIP Trunking\n- Verify Origination/Termination URIs are correct\n- Check for SIP 403 Forbidden — may be IP ACL issue\n- SIP 404: number not configured in Twilio > Phone Numbers\n- SIP 503: Twilio service issue — check https://status.twilio.com/\n- Check call logs in Twilio Console > Monitor > Logs > Calls\n\nTwilio Docs: https://www.twilio.com/docs/sip-trunking\nTwilio Console: https://console.twilio.com/', 'instruction');

-- ── Meredith Palmer (Backup/Spanning) ─────────────────────────────────

INSERT INTO agent_skills (agent_name, title, content, skill_type) VALUES
('meredith_palmer', 'Spanning M365 Backup Recovery', E'Spanning Backup for M365 step-by-step recovery:\n\n## Recover Deleted Emails\n1. Spanning Admin Console > Users > search for user\n2. Click user > Browse Backup > Mail\n3. Navigate to the date BEFORE deletion occurred\n4. Select emails > click "Restore"\n5. Choose: Restore in-place or to a different folder\n6. Verify restoration with the end user\n\n## Recover OneDrive Files\n1. Spanning Admin Console > Users > search for user\n2. Click user > Browse Backup > OneDrive\n3. Navigate to the folder/file and select point-in-time\n4. Select files > "Restore" or "Download"\n5. For large restores, use "Download" to get a ZIP file\n\n## Recover SharePoint Site\n1. Spanning Admin Console > SharePoint\n2. Search for the site by URL\n3. Browse to the date before the issue\n4. Select items > Restore or Download\n5. Note: full site restore may take hours for large sites\n\n## Cross-User Restore\n- Can restore one user''s backup to another user''s mailbox\n- Useful for employee departures or mailbox migrations\n- Select source user > Browse > Restore to > select destination\n\nSpanning Help: https://spanning.zendesk.com/', 'procedure'),

('meredith_palmer', 'Spanning Error Code Quick Reference', E'Quick reference for common Spanning error codes:\n\n| Code | Meaning | Fix |\n|------|---------|-----|\n| 14001 | Auth failure | Re-authorize in Spanning Settings |\n| 14010 | SharePoint site inaccessible | Check site exists, permissions |\n| 14020 | Mailbox not found | Verify user has Exchange license |\n| 14021 | Microsoft throttling | Wait 4-6 hours, transient |\n| 14030 | OneDrive quota exceeded | User''s drive is full |\n\nIf error persists >24h, open a ticket with Spanning support.\nSpanning Error Guide: https://spanning.zendesk.com/hc/en-us/articles/207566426-Error-Codes', 'instruction');

-- ── Oscar Martinez (Backup/Cove) ──────────────────────────────────────

INSERT INTO agent_skills (agent_name, title, content, skill_type) VALUES
('oscar_martinez', 'Cove Backup Manager Troubleshooting', E'Cove Backup Manager (N-able) troubleshooting steps:\n\n## Agent Not Connecting\n1. Check service: `Get-Service "Backup Service Controller"` (Windows)\n2. Restart: `Restart-Service "Backup Service Controller"`\n3. Check logs: `C:\\ProgramData\\MXB\\Backup Manager\\logs\\`\n4. Verify connectivity: device must reach `*.backup.management` on port 443\n5. Check system clock — significant drift causes auth failures\n6. If agent corrupted: uninstall, delete `C:\\ProgramData\\MXB`, reinstall from console\n\n## VSS Failures\n1. List VSS writers: `vssadmin list writers` — look for "Failed" or "Waiting for completion"\n2. Restart VSS: `net stop vss && net start vss`\n3. If specific writer fails, restart that application (e.g., SQL Server, Exchange)\n4. Check shadow storage: `vssadmin list shadowstorage`\n5. Resize: `vssadmin resize shadowstorage /for=C: /on=C: /maxsize=10GB`\n6. Check for conflicting backup software (only one VSS-aware backup should run)\n\n## Slow Backups\n1. Check bandwidth: Cove compresses/encrypts before upload — measure upload speed\n2. Enable LocalSpeedVault for faster local restores\n3. Check if "Force full backup" was triggered — initial seedling takes longer\n4. Large change rate may indicate ransomware or large file generation\n5. Adjust backup window to off-hours if competing with business traffic\n\nCove Docs: https://documentation.n-able.com/backup/userguide/documentation/Content/home.htm', 'runbook'),

('oscar_martinez', 'Backup Architecture Best Practices', E'Best practices for MSP backup architecture:\n\n## 3-2-1 Rule\n- 3 copies of data (production + 2 backups)\n- 2 different media types (local + cloud)\n- 1 offsite copy (cloud or replicated appliance)\n\n## RPO/RTO Planning\n- RPO (Recovery Point Objective): How much data loss is acceptable? Daily backup = 24h RPO\n- RTO (Recovery Time Objective): How fast must you recover? Cloud restore = hours, local = minutes\n- Document RPO/RTO per client in Hudu/IT documentation\n\n## Testing\n- Test restores quarterly — untested backups are not backups\n- Use Cove''s automated recovery testing for servers\n- Document test results and share with client\n\n## Monitoring\n- Check failed backups DAILY — don''t wait for client to report\n- Alert on backup overdue > 24 hours\n- Monitor storage trends — predict when you''ll hit limits\n- Review unprotected data sources monthly', 'instruction');
