-- ═══════════════════════════════════════════════════════════════════════
-- Toby Flenderson skills + Michael Scott runtime context from CLAUDE.md
-- ═══════════════════════════════════════════════════════════════════════

-- ── Toby Flenderson Skills ───────────────────────────────────────────

INSERT INTO agent_skills (agent_name, title, content, skill_type) VALUES
('toby_flenderson', 'Analysis Framework', E'## What to Analyze\n\n### Tech Profiles\nFor each technician, build a behavioral profile:\n- Average response time (hours between customer reply and tech action)\n- Ticket volume (30-day and all-time)\n- Ratings from tech_reviews (great/good/needs_improvement/poor)\n- Communication score average\n- Strong categories (ticket types they handle well)\n- Weak categories (ticket types with poor ratings or slow response)\n- Work patterns (documentation habits, escalation rate, resolution time)\n\n### Customer Insights\nFor each client with 2+ tickets:\n- Recurring issues (same problem type coming back)\n- Top issue categories\n- Update request frequency (indicates satisfaction problems)\n- Environment notes learned from tickets (apps, hardware, network setup)\n\n### Trend Detection\nLook for:\n- Spikes: sudden increase in a ticket type or from a specific client\n- Recurring: same issue happening weekly/monthly\n- Anomaly: unusual patterns (ticket at 3am, unknown user, etc.)\n- Correlation: two things happening together (e.g. DNS issues always after patching)\n- Improvement/Degradation: tech getting better or worse over time\n\n### Triage Self-Evaluation\nFor resolved tickets:\n- Compare predicted priority vs actual (was it over/under-triaged?)\n- Compare predicted type vs how it was actually resolved\n- Calculate overall accuracy score\n- Generate improvement suggestions for similar future tickets', 'instruction'),

('toby_flenderson', 'Output Destinations', E'## Where Insights Go\n\n1. **Database tables**: tech_profiles, customer_insights, trend_detections, triage_evaluations — these power the web dashboard.\n2. **Michael''s memory**: Key findings stored as shared memories so all agents benefit from the analysis.\n3. **Michael''s skills**: Updated context skills ("Toby''s Tech Profiles" and "Toby''s Customer Profiles") — injected into every future triage.\n4. **Teams notification**: Daily summary card with key findings.\n5. **Run log**: Every analysis run tracked in toby_run_log for monitoring.', 'instruction');

-- ── Michael Scott Runtime Context (from CLAUDE.md business rules) ────
-- These skills give Michael the same operational knowledge that
-- developers have in CLAUDE.md, so he makes informed triage decisions.

INSERT INTO agent_skills (agent_name, title, content, skill_type) VALUES
('michael_scott', 'Halo Ticket Type Rules', E'## Ticket Types in Halo\n\n### Gamma Default\nThe main ticket type for real customer support tickets. These get the full triage pipeline:\n- Ryan classifies\n- Specialists run in parallel\n- Michael synthesizes\n- Halo note posted\n- Tech review generated\n\n### Alerts\nAutomated monitoring alerts (Datto, backup, 3CX, etc.). Fast-path only:\n- Erin Hannon does a quick Haiku summary\n- No specialist agents\n- No tech review\n\n### Auto-Reclassification\nIf a ticket comes in as "Gamma Default" but Ryan classifies it as an automated alert, the system should change the ticket type in Halo to "Alerts". This keeps the dispatch queue clean.\n\n### What NOT to Triage\n- Alert ticket types (already handled by fast-path)\n- Closed/resolved tickets (unless re-opened by customer reply)\n- Tickets triaged less than 30 minutes ago (dedup)', 'instruction'),

('michael_scott', 'Client & Environment Context', E'## Gamma Tech Services LLC\n- MSP based in Naples, FL\n- Domains: gtmail.us, gamma.tech\n- Helpdesk: help@gamma.tech\n- When you see gtmail.us or gamma.tech, that is the MSP itself — not a client.\n\n## Client Profile\n- Typical client size: Mixed SMB (5-100 users per client)\n- Almost all clients use Microsoft 365 for email\n- No VIP distinction currently — all clients treated equally\n\n## Live Integrations (as of March 2026)\n- Hudu (documentation) — LIVE, always runs\n- Datto RMM (endpoints) — LIVE\n- JumpCloud (identity) — LIVE\n- All other integrations are planned but not live yet\n\n## Customer Mappings\n- Auto-matched by company name between Halo and each integration\n- No manual mapping required', 'context'),

('michael_scott', 'Triage Output Quality Standards', E'## What Techs Want\n- Keep the current structured format (table/sections) but CUT THE FILLER\n- Every sentence must carry useful information\n- Do NOT pad with obvious statements like "This ticket appears to be about a computer issue"\n- Be specific and actionable — what should the tech DO?\n\n## What''s Missing (improve these)\n- **Hudu context**: Pull relevant client docs, network diagrams, known issues, and previous procedures. Techs currently have to go look this up manually.\n- **Datto device info**: If the ticket mentions a specific device, include its status, recent alerts, and patch status from Datto RMM.\n\n## Retriage Notes\n- Small change (customer says "thanks" or provides minor info) = compact diff note\n- Big change (new symptoms, escalation, priority shift) = full retriage note\n- Don''t repeat the entire original triage for trivial updates\n\n## Update Requests\n- When a customer asks for an update, only alert the team internally\n- Do NOT draft customer responses — the tech decides what to say\n- Teams alert should fire immediately (within the webhook handler)', 'instruction');
