-- ═══════════════════════════════════════════════════════════════════════
-- Toby Flenderson — Learning & Analytics Agent Tables
--
-- Stores insights generated by the background learning agent:
-- 1. Tech profiles — per-technician behavior patterns
-- 2. Customer insights — per-client recurring patterns
-- 3. Trend detections — cross-ticket pattern alerts
-- 4. Triage evaluations — self-assessment of AI accuracy
-- ═══════════════════════════════════════════════════════════════════════

-- ── Tech Profiles ────────────────────────────────────────────────────
-- One row per tech, updated daily by Toby's analysis.

CREATE TABLE tech_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tech_name TEXT NOT NULL UNIQUE,
  -- Response metrics
  avg_response_hours NUMERIC(8,2),
  median_response_hours NUMERIC(8,2),
  fastest_response_hours NUMERIC(8,2),
  slowest_response_hours NUMERIC(8,2),
  -- Volume
  tickets_handled_30d INT NOT NULL DEFAULT 0,
  tickets_handled_all_time INT NOT NULL DEFAULT 0,
  -- Ratings from tech_reviews
  avg_rating_score NUMERIC(3,2),  -- great=4, good=3, needs_improvement=2, poor=1
  avg_communication_score NUMERIC(3,2),
  great_count INT NOT NULL DEFAULT 0,
  good_count INT NOT NULL DEFAULT 0,
  needs_improvement_count INT NOT NULL DEFAULT 0,
  poor_count INT NOT NULL DEFAULT 0,
  -- Strengths & weaknesses (ticket types)
  strong_categories TEXT[] DEFAULT '{}',   -- ticket types they excel at
  weak_categories TEXT[] DEFAULT '{}',     -- ticket types they struggle with
  -- Behavioral patterns
  patterns JSONB DEFAULT '{}',
  -- e.g. { "avg_notes_per_ticket": 3.2, "documents_work": true,
  --        "typical_resolution_hours": 12, "escalation_rate": 0.05 }
  summary TEXT,  -- AI-generated summary of this tech's work style
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_tech_profiles_name ON tech_profiles(tech_name);

-- ── Customer Insights ────────────────────────────────────────────────
-- One row per client, updated daily.

CREATE TABLE customer_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_name TEXT NOT NULL UNIQUE,
  client_id INT,
  -- Volume
  tickets_30d INT NOT NULL DEFAULT 0,
  tickets_all_time INT NOT NULL DEFAULT 0,
  -- Patterns
  top_issue_types TEXT[] DEFAULT '{}',       -- most common ticket classification types
  recurring_issues TEXT[] DEFAULT '{}',      -- issues that keep coming back
  avg_urgency NUMERIC(3,2),
  -- Satisfaction signals
  update_request_count_30d INT NOT NULL DEFAULT 0,  -- how often they ask for updates
  avg_tech_response_hours NUMERIC(8,2),
  -- Environment notes (learned from tickets)
  environment_notes JSONB DEFAULT '{}',
  -- e.g. { "primary_firewall": "FortiGate", "domain": "acme.local",
  --        "user_count": 45, "common_apps": ["QuickBooks", "Outlook"] }
  summary TEXT,  -- AI-generated summary of this client's patterns
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_customer_insights_name ON customer_insights(client_name);
CREATE INDEX idx_customer_insights_client_id ON customer_insights(client_id);

-- ── Trend Detections ─────────────────────────────────────────────────
-- Individual trend/pattern entries detected by Toby.

CREATE TABLE trend_detections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  trend_type TEXT NOT NULL
    CHECK (trend_type IN (
      'spike', 'recurring', 'seasonal', 'anomaly', 'correlation', 'improvement', 'degradation'
    )),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  severity TEXT NOT NULL DEFAULT 'info'
    CHECK (severity IN ('critical', 'warning', 'info')),
  -- What triggered this detection
  affected_entity TEXT,              -- tech name, client name, or ticket type
  affected_entity_type TEXT          -- 'tech', 'client', 'category', 'global'
    CHECK (affected_entity_type IN ('tech', 'client', 'category', 'global')),
  -- Evidence
  evidence JSONB DEFAULT '{}',
  -- e.g. { "ticket_ids": [123, 456], "count": 5, "time_range": "2026-03-14 to 2026-03-21",
  --        "baseline": 2, "current": 8 }
  -- Actionability
  recommendation TEXT,
  is_acknowledged BOOLEAN NOT NULL DEFAULT false,
  acknowledged_by UUID REFERENCES profiles(id),
  acknowledged_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_trend_detections_type ON trend_detections(trend_type);
CREATE INDEX idx_trend_detections_severity ON trend_detections(severity);
CREATE INDEX idx_trend_detections_created ON trend_detections(created_at DESC);
CREATE INDEX idx_trend_detections_entity ON trend_detections(affected_entity, affected_entity_type);

-- ── Triage Evaluations ───────────────────────────────────────────────
-- Self-assessment: how accurate were our triages for resolved tickets?

CREATE TABLE triage_evaluations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id UUID REFERENCES tickets(id) ON DELETE SET NULL,
  halo_id INT,
  triage_result_id UUID REFERENCES triage_results(id) ON DELETE SET NULL,
  -- What we predicted
  predicted_priority INT,
  predicted_type TEXT,
  predicted_urgency INT,
  -- What actually happened
  actual_resolution_hours NUMERIC(8,2),
  actual_was_escalated BOOLEAN,
  actual_required_onsite BOOLEAN,
  -- Accuracy assessment
  priority_accurate BOOLEAN,
  type_accurate BOOLEAN,
  urgency_accurate BOOLEAN,
  overall_accuracy NUMERIC(3,2),  -- 0-1 composite score
  -- Learnings
  what_we_missed TEXT,            -- AI explanation of what the triage got wrong
  what_we_got_right TEXT,
  improvement_suggestion TEXT,    -- how to do better next time
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_triage_evaluations_ticket ON triage_evaluations(ticket_id);
CREATE INDEX idx_triage_evaluations_created ON triage_evaluations(created_at DESC);
CREATE INDEX idx_triage_evaluations_accuracy ON triage_evaluations(overall_accuracy);

-- ── Toby Run Log ─────────────────────────────────────────────────────
-- Track each Toby analysis run for monitoring and debugging.

CREATE TABLE toby_run_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_type TEXT NOT NULL
    CHECK (run_type IN ('daily', 'manual', 'weekly')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  -- Scope
  tickets_analyzed INT NOT NULL DEFAULT 0,
  tech_profiles_updated INT NOT NULL DEFAULT 0,
  customer_insights_updated INT NOT NULL DEFAULT 0,
  trends_detected INT NOT NULL DEFAULT 0,
  triages_evaluated INT NOT NULL DEFAULT 0,
  memories_created INT NOT NULL DEFAULT 0,
  skills_updated INT NOT NULL DEFAULT 0,
  -- Cost
  tokens_used INT NOT NULL DEFAULT 0,
  processing_time_ms INT,
  -- Status
  status TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'completed', 'error')),
  error_message TEXT,
  summary TEXT
);

CREATE INDEX idx_toby_run_log_status ON toby_run_log(status);
CREATE INDEX idx_toby_run_log_created ON toby_run_log(started_at DESC);

-- ═══════════════════════════════════════════════════════════════════════
-- RLS Policies
-- ═══════════════════════════════════════════════════════════════════════

ALTER TABLE tech_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE trend_detections ENABLE ROW LEVEL SECURITY;
ALTER TABLE triage_evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE toby_run_log ENABLE ROW LEVEL SECURITY;

-- Admins can manage all, authenticated can read
CREATE POLICY "Admins manage tech_profiles" ON tech_profiles FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Auth read tech_profiles" ON tech_profiles FOR SELECT
  USING (auth.uid() IS NOT NULL);
CREATE POLICY "Service role manage tech_profiles" ON tech_profiles FOR ALL
  USING (current_setting('role') = 'service_role');

CREATE POLICY "Admins manage customer_insights" ON customer_insights FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Auth read customer_insights" ON customer_insights FOR SELECT
  USING (auth.uid() IS NOT NULL);
CREATE POLICY "Service role manage customer_insights" ON customer_insights FOR ALL
  USING (current_setting('role') = 'service_role');

CREATE POLICY "Admins manage trend_detections" ON trend_detections FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Auth read trend_detections" ON trend_detections FOR SELECT
  USING (auth.uid() IS NOT NULL);
CREATE POLICY "Service role manage trend_detections" ON trend_detections FOR ALL
  USING (current_setting('role') = 'service_role');

CREATE POLICY "Admins manage triage_evaluations" ON triage_evaluations FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Auth read triage_evaluations" ON triage_evaluations FOR SELECT
  USING (auth.uid() IS NOT NULL);
CREATE POLICY "Service role manage triage_evaluations" ON triage_evaluations FOR ALL
  USING (current_setting('role') = 'service_role');

CREATE POLICY "Admins manage toby_run_log" ON toby_run_log FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Auth read toby_run_log" ON toby_run_log FOR SELECT
  USING (auth.uid() IS NOT NULL);
CREATE POLICY "Service role manage toby_run_log" ON toby_run_log FOR ALL
  USING (current_setting('role') = 'service_role');

-- Enable realtime for trend detections (useful for dashboard alerts)
ALTER PUBLICATION supabase_realtime ADD TABLE trend_detections;
ALTER PUBLICATION supabase_realtime ADD TABLE toby_run_log;

-- ── Seed Toby's cron job ─────────────────────────────────────────────

INSERT INTO cron_jobs (name, description, schedule, endpoint, is_active)
VALUES (
  'Toby Learning Analysis',
  'Daily background analysis: tech profiles, customer patterns, trend detection, triage self-evaluation',
  '0 2 * * *',
  '/toby/analyze',
  true
);
